export const LOCATION_MODULE = 'LOCATION_MODULE'
export const PROVINCES = 'PROVINCES'
export const DISTRICTS = 'DISTRICTS'
export const WARDS = 'WARDS'

export const SET_PROVINCES = 'SET_PROVINCES'
export const SET_DISTRICTS = 'SET_DISTRICTS'
export const SET_WARDS = 'SET_WARDS'

export const FETCH_DATA_PROVINCES = 'FETCH_DATA_PROVINCES'
export const FETCH_DATA_DISTRICTS = 'FETCH_DATA_DISTRICTS'
export const FETCH_DATA_WARDS = 'FETCH_DATA_WARDS'